<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);CA1707</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MSTest" />
    <ProjectReference Include="../../src/UtoAegis.Core/UtoAegis.Core.csproj" />
  </ItemGroup>
</Project>
