<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../UtoAegis.Core/UtoAegis.Core.csproj" />
    <ProjectReference Include="../UtoAegis.Infrastructure/UtoAegis.Infrastructure.csproj" />
  </ItemGroup>
</Project>
